# 0,1,2,3
OPT_LEVEL := 3
# 0 - nodebug, 1 - debug
DEBUG := 0
# arch flags
ARCH_FLAGS := -march=native -mtune=native
# extra cflags
EXTRA_CFLAGS := -DHA_ONLY_LE
# extra ldflags
EXTRA_LDLAGS := # -flto
