name: [   BIG-ENDIAN] [   ARM] On Ubuntu [ GCC]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU for ARM big-endian
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Set up Docker for ARM big-endian
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build and test in ARM big-endian environment
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace \
          multiarch/debian-debootstrap:armeb-buster \
          /bin/bash -c "
            apt-get update && \
            apt-get install -y gcc make && \
            make all install check uninstall clean CC='gcc -mbig-endian'
          "

    - name: Benchmark in ARM big-endian environment
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace \
          multiarch/debian-debootstrap:armeb-buster \
          /bin/bash -c "
            apt-get update && \
            apt-get install -y gcc make && \
            make all install bench uninstall clean CC='gcc -mbig-endian'
          "