name: "[   BIG-ENDIAN] [   ARM] On Ubuntu [ GCC]"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU and ARM big-endian rootfs
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static wget
        wget https://example.com/path/to/armeb-rootfs.tar.gz
        mkdir -p armeb-rootfs
        sudo tar -xzf armeb-rootfs.tar.gz -C armeb-rootfs
        sudo cp /usr/bin/qemu-arm-static armeb-rootfs/usr/bin/
      
    - name: Build and test in ARM big-endian environment
      run: |
        sudo chroot armeb-rootfs /bin/bash -c "
          apt-get update && \
          apt-get install -y gcc make && \
          cd /workspace && \
          make all install check uninstall clean CC="gcc -mbig-endian"
        "
