name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Performing test
      run: sudo make all install check uninstall clean

    - name: Performing benchmark
      run: sudo make all install bench uninstall clean
