name: "CI/CD on tcc"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configuring
      run: |
        make autoconfig
      
    - name: Building
      run: |
        make all CC=tcc

    - name: Instaslling
      run: |
        sudo make install

    - name: Performing test
      run: |
        make check

    - name: Performing benchmark
      run: |
        make bench

    - name: Cleanup
      run: |
        make clean

