name: "[LITTLE-ENDIAN] [x86_64] On Ubuntu [ GCC]"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Performing test
      run: |
        sudo make all install checkall uninstall clean CC=gcc

    - name: Performing benchmark
      run: |
        sudo make all install bench uninstall clean CC=gcc
