name: "[LITTLE-ENDIAN] [x86_64] On Ubuntu [LLVM]"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Performing test
      run: |
        sudo make -f "Makefile.old" all install checkall uninstall clean CC=clang

    - name: Performing benchmark
      run: |
        sudo make -f "Makefile.old" all install bench uninstall clean CC=clang
