name: (x86_64) On Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set ulimit for core dumps
      run: |
        ulimit -c unlimited

    - name: Install necessary packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gdb

    - name: Performing test
      run: |
        sudo make all install checkall uninstall clean || (echo "Segmentation fault occurred"; gdb -batch -ex "bt" -ex "quit" ./bin/unit)

    - name: Performing benchmark
      run: |
        sudo make all install bench uninstall clean
